pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success=continuous-integration/travis-ci/pr
    actions:
      merge:
        method: merge
  - name: automatic delete head branch on merged pull requests
    conditions:
      - merged
      - base!=develop
    actions:
      delete_head_branch