version: "3.7"

services:
  postgres:
    image: postgres:10
    volumes:
      - .pgdata:/var/lib/postgresql/data
    env_file: ./.envs/.production/.env
    build:
      context: ./postgres

  django:
    build: ./src
    command: gunicorn -b :9000 -w 3 api_pairgame.wsgi:application --reload --timeout 3600
    volumes:
      - ./src:/src
    depends_on:
      - postgres
      - redis
    env_file: ./.envs/.production/.env

  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    volumes:
      - ./src/static:/static
      - ./src/media:/media
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on: 
      - django
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
