version: "3.7"
services:
  postgres:
    image: postgres:10
    volumes:
      - .pgdata:/var/lib/postgresql/data
    env_file: ./.envs/.local/.env
    build:
      context: ./postgres

  django:
    build: ./src
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/src
    depends_on:
      - postgres
    env_file: ./.envs/.local/.env
    ports:
      - "8000:8000"

  redis:
    container_name: api_pairgame_redis
    restart: always
    image: redis:5.0
    env_file: ./.envs/.local/.env

  celery:
    build: ./src
    command: celery -A api_pairgame worker -l info
    env_file: ./.envs/.local/.env
    volumes:
      - ./src:/src
    depends_on:
      - redis
      - django 
  
  celery-beat:
    build: ./src
    command: celery -A api_pairgame beat -l info
    env_file: ./.envs/.local/.env
    volumes:
      - ./src:/src
    depends_on:
      - redis
      - django 